Feature/sensitive arguments as envvars
sensu/sensu-slack-handler pull request #12
Opened 2019-01-04 08:25 UTC by jspaleta

Treat webhook as sensitive, default to taking value from SLACK_WEBHOOK_URL envvar

2019-01-04 14:47 UTC, nikkictl requested changes
Same comments here as sensu-influxdb-handler:
- update help usage in readme
- call out environment variables in readme
- need "Unreleased" changelog entry

Thanks for these improvements Jef, looking great so far!

2019-01-05 02:06 UTC, jspaleta commented
requested changes added in latest commit

2019-01-05 02:30 UTC, jspaleta commented
i'm doing some more testing locally to make sure this works.

2019-01-07 16:52 UTC, nikkictl approved these changes

2019-01-08 18:49 UTC, merged