Updating readme for clarity
sensu/sensu-slack-handler pull request #23
Opened 2019-09-19 15:31 UTC by asachs01

The current readme's first instructions to users is to install the plugin by building the plugin from source. This goes against our recommended practice of using Bonsai for downloading/installing plugins. The changes here attempt to be a bit more prescriptive and tell users to install the asset from Bonsai, as well as provide some example json/yml bits for configuration/installation

2019-09-19 15:50 UTC, cwjohnston requested changes

2019-09-19 15:50 UTC, cwjohnston commented on README.md
> +`sensuctl asset add sensu/sensu-slack-handler:1.0.3`
I know I gave an example with the version included, but I think leaving it out will keep things low-touch and avoid the perception that the readme is out of date.

```suggestion
`sensuctl asset add sensu/sensu-slack-handler`
```

2019-09-19 15:50 UTC, cwjohnston commented on README.md
> +If you're using an earlier version of sensuctl, you can find the asset on the [Bonsai Asset Index](https://bonsai.sensu.io/assets/sensu/sensu-slack-handler).
```suggestion
If you're using an earlier version of sensuctl, you can download the asset definition from [this project's Bonsai Asset Index page](https://bonsai.sensu.io/assets/sensu/sensu-slack-handler).
```

2019-09-19 15:50 UTC, cwjohnston commented on README.md
> +        "runtime_assets": ["sensu-slack-handler_linux_amd64"]
Let's check that `asset add` produces an asset name like this one... I hope it is installing multi-build asset definitions with simpler names...

2019-09-24 15:50 UTC, asachs01 commented
@cwjohnston looks like it installs the multi-build w/ sane names:

```
                 Name                                                      URL                                         Hash
 ──────────────────────────────────── ────────────────────────────────────────────────────────────────────────────── ─────────
  sensu-aggregate-check                //assets.bonsai.sensu.io/.../sensu-aggregate-check_0.0.7_linux_amd64.tar.gz    de6f2f5
  sensu-email-handler                  //assets.bonsai.sensu.io/.../sensu-email-handler_0.2.0_linux_amd64.tar.gz      d69df76
  sensu-go-cpu-check-linux             //assets.bonsai.sensu.io/.../sensu-go-cpu-check_0.0.3_linux_amd64.tar.gz       487ab34
  sensu-go-fatigue-check-filter        //assets.bonsai.sensu.io/.../sensu-go-fatigue-check-filter_0.2.0.tar.gz        a621481
  sensu-go-has-contact-filter          //assets.bonsai.sensu.io/.../sensu-go-has-contact-filter_0.2.0.tar.gz          d07584d
  sensu-go-hello-world-asset           //github.com/.../sensu-go-hello-world-0.0.7.tar.gz                             9c9c511
  sensu-go-hook-has-process-filter     //assets.bonsai.sensu.io/.../sensu-go-hook-has-process-filter_0.0.3.tar.gz     c05e89d
  sensu-go-remediation-handler         //github.com/.../sensu-go-remediation-handler_0.9.0_linux_amd64.tar.gz         5a5f07a
  sensu-influxdb-handler_linux_amd64   //assets.bonsai.sensu.io/.../sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz   612c6ff
  sensu-slack-handler                  //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_linux_amd64.tar.gz      6872086
  sensu/sensu-slack-handler            //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_linux_amd64.tar.gz      6872086
  sensu/sensu-slack-handler            //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_linux_386.tar.gz        d9040ae
  sensu/sensu-slack-handler            //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_linux_arm64.tar.gz      b492ae2
  sensu/sensu-slack-handler            //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_linux_armv7.tar.gz      362fe51
  sensu/sensu-slack-handler            //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_darwin_amd64.tar.gz     88bbdca
  sensu/sensu-slack-handler            //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_darwin_386.tar.gz       e2d7d0d
  sensu/sensu-slack-handler            //assets.bonsai.sensu.io/.../sensu-slack-handler_1.0.3_windows_amd64.tar.gz    53359fa
```

2019-09-24 18:53 UTC, merged